### ISSUE TITLE
[EPIC KR1] Assemble ROSA Documentation Text

### ISSUE THREAD

**Issue by Shreyanand** [redhat-et/foundation-models-for-documentation#7]
The first step to train a QA model for ROSA documentation search is to assemble and process the documentation text from various sources. This issue should focus on solving the following steps:

- [x] #3 
- [x] Collect PDFs of product and FAQ pages for ROSA
- [x] #4 
- [x] #6

**Comment by codificat** [comment]
I believe this is complete enough for now, so closing it.
